# csharp+phangomjs
language: csharp
dist: trusty
dotnet: 2.0.0
sudo: required
cache:
  directories:
    - "travis_phantomjs"
before_install:
  - phantomjs --version
  - dotnet --info
  - dotnet --version
script:
  - dotnet restore
  - dotnet run ip http://1212.ip138.com/ic.asp png 
  - dotnet run acfun http://www.acfun.cn/ jpg 20
  - dotnet run bilibili https://www.bilibili.com jpg 20
  - dotnet run youtube https://www.youtube.com jpg 20
  - dotnet run google https://www.google.com
    
after_script:
  - folder="download"
  - if [ ! -x "$folder"]; then  mkdir "$folder" fi
  - cd download
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "down img"
  - git remote add orginimgs "https://${GH_TOKEN}@${GH_REF}"
  - export abc='date +%Y%m%d'
  - echo "year:$($abc)"
  - git push --force --quiet orginimgs master:${P_BRANCH}
  - git push --force --quiet orginimgs master:${P_BRANCH}_$($abc)

branches:
  only:
    - master
